version: "2"

linters:
  enable:
    - unused
    - bodyclose
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - gocyclo
    

formatters:
  enable:
    - gofmt

run:
  timeout: 2m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0