// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package product

import (
	"context"
	"go-pet-shop/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewProductsMock creates a new instance of ProductsMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductsMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductsMock {
	mock := &ProductsMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProductsMock is an autogenerated mock type for the Products type
type ProductsMock struct {
	mock.Mock
}

type ProductsMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductsMock) EXPECT() *ProductsMock_Expecter {
	return &ProductsMock_Expecter{mock: &_m.Mock}
}

// CreateProduct provides a mock function for the type ProductsMock
func (_mock *ProductsMock) CreateProduct(ctx context.Context, product models.Product) (int, error) {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Product) (int, error)); ok {
		return returnFunc(ctx, product)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Product) int); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Product) error); ok {
		r1 = returnFunc(ctx, product)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductsMock_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type ProductsMock_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - product models.Product
func (_e *ProductsMock_Expecter) CreateProduct(ctx any, product any) *ProductsMock_CreateProduct_Call {
	return &ProductsMock_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, product)}
}

func (_c *ProductsMock_CreateProduct_Call) Run(run func(ctx context.Context, product models.Product)) *ProductsMock_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Product
		if args[1] != nil {
			arg1 = args[1].(models.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductsMock_CreateProduct_Call) Return(n int, err error) *ProductsMock_CreateProduct_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *ProductsMock_CreateProduct_Call) RunAndReturn(run func(ctx context.Context, product models.Product) (int, error)) *ProductsMock_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function for the type ProductsMock
func (_mock *ProductsMock) DeleteProduct(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductsMock_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type ProductsMock_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *ProductsMock_Expecter) DeleteProduct(ctx any, id any) *ProductsMock_DeleteProduct_Call {
	return &ProductsMock_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", ctx, id)}
}

func (_c *ProductsMock_DeleteProduct_Call) Run(run func(ctx context.Context, id int)) *ProductsMock_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductsMock_DeleteProduct_Call) Return(err error) *ProductsMock_DeleteProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductsMock_DeleteProduct_Call) RunAndReturn(run func(ctx context.Context, id int) error) *ProductsMock_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllProducts provides a mock function for the type ProductsMock
func (_mock *ProductsMock) GetAllProducts(ctx context.Context) ([]models.Product, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllProducts")
	}

	var r0 []models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Product, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Product); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductsMock_GetAllProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllProducts'
type ProductsMock_GetAllProducts_Call struct {
	*mock.Call
}

// GetAllProducts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ProductsMock_Expecter) GetAllProducts(ctx any) *ProductsMock_GetAllProducts_Call {
	return &ProductsMock_GetAllProducts_Call{Call: _e.mock.On("GetAllProducts", ctx)}
}

func (_c *ProductsMock_GetAllProducts_Call) Run(run func(ctx context.Context)) *ProductsMock_GetAllProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ProductsMock_GetAllProducts_Call) Return(products []models.Product, err error) *ProductsMock_GetAllProducts_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *ProductsMock_GetAllProducts_Call) RunAndReturn(run func(ctx context.Context) ([]models.Product, error)) *ProductsMock_GetAllProducts_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProduct provides a mock function for the type ProductsMock
func (_mock *ProductsMock) UpdateProduct(ctx context.Context, product models.Product) error {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Product) error); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductsMock_UpdateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProduct'
type ProductsMock_UpdateProduct_Call struct {
	*mock.Call
}

// UpdateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - product models.Product
func (_e *ProductsMock_Expecter) UpdateProduct(ctx any, product any) *ProductsMock_UpdateProduct_Call {
	return &ProductsMock_UpdateProduct_Call{Call: _e.mock.On("UpdateProduct", ctx, product)}
}

func (_c *ProductsMock_UpdateProduct_Call) Run(run func(ctx context.Context, product models.Product)) *ProductsMock_UpdateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Product
		if args[1] != nil {
			arg1 = args[1].(models.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductsMock_UpdateProduct_Call) Return(err error) *ProductsMock_UpdateProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductsMock_UpdateProduct_Call) RunAndReturn(run func(ctx context.Context, product models.Product) error) *ProductsMock_UpdateProduct_Call {
	_c.Call.Return(run)
	return _c
}
